### ISSUE TITLE
Planned to integrate the new camera stack?

### ISSUE THREAD

**Issue by dl9sec** [paukstelis/octoprint_install#17]
Hi,
is it planned to integrate  the new camera streaming setup based on "camera-streamer"?

Thanks.

Regards, Thorsten

**Comment by paukstelis** [comment]
That camera stack is specific to OctoPi and using a Raspberry Pi. In that sense, there is no way to directly replicate the camera stack, and really no need because octoprint_deploy/install has its own method for creating camera service (that is better, IMO, since the new camera stack has you pick a camera from a list rather than detect a camera directly). I have looked into including camera_streamer which is used by the new camera stack. There are issues there with dependencies and which features can be made available to camera_streamer. I am not well enough versed in how it functions to include it at this time.

**Comment by dl9sec** [comment]
Thank you very much for the reply.
I think that camera-streamer itself isn't OctoPi specific, but the scripts and systemd magic around camera-streamer.
But it seems to be the same thing with the current camera setup in your installation script. The OctoPi "magic" is stripped down to a very basic camera setup.
Maybe I will do some tests with camera-streamer  on my own an will keep you in the loop about the results...

Regards, Thorsten

**Comment by paukstelis** [comment]
closing for archive
